# Generated by Django 3.2.5 on 2022-02-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0007_alter_myuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='image',
        ),
        migrations.AddField(
            model_name='myuser',
            name='hide_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='get_default_profile_image', null=True, upload_to='get_profile_image_filepath'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default=0, max_length=100, unique=True, verbose_name='user name'),
            preserve_default=False,
        ),
    ]
