# Generated by Django 3.2.5 on 2022-02-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0008_auto_20220208_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='get_profile_image_filepath'),
        ),
    ]
