# Generated by Django 3.2.5 on 2022-02-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0010_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.CharField(blank=True, max_length=200, null=True)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
            ],
        ),
    ]
