# Generated by Django 3.2.5 on 2022-02-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0012_alter_uploadfiles_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('year', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='filecourse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DimosoApp.filecourse'),
            preserve_default=False,
        ),
    ]
