# Generated by Django 3.2.5 on 2022-02-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0015_message_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='username',
        ),
    ]
