# Generated by Django 3.2.5 on 2022-02-16 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0016_rename_user_message_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(blank=True, max_length=10000000, null=True),
        ),
    ]
