# Generated by Django 3.2.5 on 2022-02-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0018_alter_message_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Messages',
        ),
    ]
