# Generated by Django 3.2.5 on 2022-02-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0020_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
